#!/bin/sh
set -e
################################################################################
#
#      Author:		Bob Fisch
#
#      Description:	
#
################################################################################
#
#      Revision List
#
#      Author						Date		Description
#      ------						----		-----------
#      Bob Fisch					2008.10.04  First Issue
#      Bob Fisch					2009.07.05  FUnimozer Edition
#	   Bob Fisch & Philipp Hübner	2009.07.08  Scripting ameliorations
#
################################################################################

# delete the old archive (if present)
[ -f unimozer.jar ] && rm unimozer.jar

# create an new archive
jar cmf unimozer.manifest unimozer.jar -C bin/ .

# execute the archive
java -jar unimozer.jar