#!/bin/sh
set -e
################################################################################
#
#      Author:		Klaus-Peter Reimers
#
#      Description:	This script compiles the source code, 
#			generates a standard java application
#			and then runs the application
#
################################################################################
#
#      Revision List
#
#      Author						Date			Description
#      ------						----			-----------
#      Klaus-Peter Reimers      	2008.06.04      First Issue
#      Bob Fisch					2008.06.06      Script modified to work within
#													an Eclipse project	
#	   Bob Fisch               	 	2009.07.05      Updated for Unimozer
#	   Bob Fisch & Philipp Hübner	2009.07.08  	Scripting ameliorations
#	   Bob Fisch					2010.01.25		Update for new RSyntasTextArea	
#
################################################################################

# delete old class files from "lu" package
echo Removing .class files
find src -name '*.class' -exec rm {} \;
find bin -name '*.class' -exec rm {} \;

# change into the "src" directory
echo Changing into src directory
cd src

# compile the application itselfecho Compiling Structorizer
echo "Compiling RSyntaxTextArea - IO"
javac -d ../bin/ -cp ../bin/:.:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/janino.jar:../lib/beansbinding-1.2.1.jar:../lib/Structorizer.jar:../lib/freehep.jar:../lib/freehep-swing-2.0.3.jar:../lib/freehep-graphicsio-2.1.1.jar:../lib/freehep-xml-2.1.1.jar:../lib/freehep-graphics2d-2.1.1.jar:../lib/freehep-io-2.0.2.jar:../lib/freehep-util-2.0.2.jar:../lib/freehep-graphicsio-svg-2.1.1.jar org/fife/io/*.java
echo "Compiling RSyntaxTextArea - Print"
javac -d ../bin/ -cp ../bin/:.:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/janino.jar:../lib/beansbinding-1.2.1.jar:../lib/Structorizer.jar:../lib/freehep.jar:../lib/freehep-swing-2.0.3.jar:../lib/freehep-graphicsio-2.1.1.jar:../lib/freehep-xml-2.1.1.jar:../lib/freehep-graphics2d-2.1.1.jar:../lib/freehep-io-2.0.2.jar:../lib/freehep-util-2.0.2.jar:../lib/freehep-graphicsio-svg-2.1.1.jar org/fife/print/*.java
echo "Compiling RSyntaxTextArea - Util"
javac -d ../bin/ -cp ../bin/:.:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/janino.jar:../lib/beansbinding-1.2.1.jar:../lib/Structorizer.jar:../lib/freehep.jar:../lib/freehep-swing-2.0.3.jar:../lib/freehep-graphicsio-2.1.1.jar:../lib/freehep-xml-2.1.1.jar:../lib/freehep-graphics2d-2.1.1.jar:../lib/freehep-io-2.0.2.jar:../lib/freehep-util-2.0.2.jar:../lib/freehep-graphicsio-svg-2.1.1.jar org/fife/util/*.java
echo "Compiling RSyntaxTextArea - Rsyntaxtextarea"
javac -d ../bin/ -cp ../bin/:.:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/janino.jar:../lib/beansbinding-1.2.1.jar:../lib/Structorizer.jar:../lib/freehep.jar:../lib/freehep-swing-2.0.3.jar:../lib/freehep-graphicsio-2.1.1.jar:../lib/freehep-xml-2.1.1.jar:../lib/freehep-graphics2d-2.1.1.jar:../lib/freehep-io-2.0.2.jar:../lib/freehep-util-2.0.2.jar:../lib/freehep-graphicsio-svg-2.1.1.jar org/fife/ui/rsyntaxtextarea/*.java
echo "Compiling RSyntaxTextArea - Rsyntaxtextarea - Modes"
javac -d ../bin/ -cp ../bin/:.:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/janino.jar:../lib/beansbinding-1.2.1.jar:../lib/Structorizer.jar:../lib/freehep.jar:../lib/freehep-swing-2.0.3.jar:../lib/freehep-graphicsio-2.1.1.jar:../lib/freehep-xml-2.1.1.jar:../lib/freehep-graphics2d-2.1.1.jar:../lib/freehep-io-2.0.2.jar:../lib/freehep-util-2.0.2.jar:../lib/freehep-graphicsio-svg-2.1.1.jar org/fife/ui/rsyntaxtextarea/modes/*.java
echo "Compiling RSyntaxTextArea - Rsyntaxtextarea - Templates"
javac -d ../bin/ -cp ../bin/:.:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/janino.jar:../lib/beansbinding-1.2.1.jar:../lib/Structorizer.jar:../lib/freehep.jar:../lib/freehep-swing-2.0.3.jar:../lib/freehep-graphicsio-2.1.1.jar:../lib/freehep-xml-2.1.1.jar:../lib/freehep-graphics2d-2.1.1.jar:../lib/freehep-io-2.0.2.jar:../lib/freehep-util-2.0.2.jar:../lib/freehep-graphicsio-svg-2.1.1.jar org/fife/ui/rsyntaxtextarea/templates/*.java
echo "Compiling RSyntaxTextArea - Autocomplete"
javac -d ../bin/ -cp ../bin/:.:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/janino.jar:../lib/beansbinding-1.2.1.jar:../lib/Structorizer.jar:../lib/freehep.jar:../lib/freehep-swing-2.0.3.jar:../lib/freehep-graphicsio-2.1.1.jar:../lib/freehep-xml-2.1.1.jar:../lib/freehep-graphics2d-2.1.1.jar:../lib/freehep-io-2.0.2.jar:../lib/freehep-util-2.0.2.jar:../lib/freehep-graphicsio-svg-2.1.1.jar org/fife/ui/autocomplete/*.java
echo "Compiling RSyntaxTextArea - Rtextarea"
javac -d ../bin/ -cp ../bin/:.:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/janino.jar:../lib/beansbinding-1.2.1.jar:../lib/Structorizer.jar:../lib/freehep.jar:../lib/freehep-swing-2.0.3.jar:../lib/freehep-graphicsio-2.1.1.jar:../lib/freehep-xml-2.1.1.jar:../lib/freehep-graphics2d-2.1.1.jar:../lib/freehep-io-2.0.2.jar:../lib/freehep-util-2.0.2.jar:../lib/freehep-graphicsio-svg-2.1.1.jar org/fife/ui/rtextarea/*.java
echo "Compiling Unimozer"
javac -d ../bin/ -cp ../bin/:.:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/janino.jar:../lib/beansbinding-1.2.1.jar:../lib/Structorizer.jar:../lib/freehep.jar:../lib/freehep-swing-2.0.3.jar:../lib/freehep-graphicsio-2.1.1.jar:../lib/freehep-xml-2.1.1.jar:../lib/freehep-graphics2d-2.1.1.jar:../lib/freehep-io-2.0.2.jar:../lib/freehep-util-2.0.2.jar:../lib/freehep-graphicsio-svg-2.1.1.jar lu/fisch/unimozer/Main.java

# copying some other files to binary tree
echo Copying ressources
rm -R -f ../bin/lu/fisch/icons 
mkdir ../bin/lu/fisch/icons 
cp -R lu/fisch/icons/* ../bin/lu/fisch/icons/
cp -R lu/fisch/unimozer/*.txt ../bin/lu/fisch/unimozer/
cp -R org/fife/ui/rsyntaxtextarea/modes/*.flex ../bin/org/fife/ui/rsyntaxtextarea/modes/
cp -R org/fife/ui/rsyntaxtextarea/*.properties ../bin/org/fife/ui/rsyntaxtextarea/
cp -R org/fife/ui/rsyntaxtextarea/focusabletip/*.properties ../bin/org/fife/ui/rsyntaxtextarea/focusabletip/
cp -R org/fife/ui/rtextarea/*.properties ../bin/org/fife/ui/rtextarea/

# changing into binary directory
echo Changing into binary directory
cd ../bin/

# run the application
echo Running Unimozer
java -cp .:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/janino.jar:../lib/beansbinding-1.2.1.jar:../lib/Structorizer.jar:../lib/freehep.jar:../lib/freehep-swing-2.0.3.jar:../lib/freehep-graphicsio-2.1.1.jar:../lib/freehep-xml-2.1.1.jar:../lib/freehep-graphics2d-2.1.1.jar:../lib/freehep-io-2.0.2.jar:../lib/freehep-util-2.0.2.jar:../lib/freehep-graphicsio-svg-2.1.1.jar lu.fisch.unimozer.Main

# move back into the folder where we started
cd ..
