#!/bin/sh
################################################################################
#
#      Author:          Klaus-Peter Reimers
#
#      Description:     This script runs the application again
#
################################################################################
#
#      Revision List
#
#      Author                                   Date            Description
#      ------                                   ----            -----------
#      Klaus-Peter Reimers      2008.06.04      First Issue
#      Bob Fisch			    2006.06.06      Script modified to work within
#						                        an Eclipse project
#	   Bob Fisch                2009.07.05      Updated for Unimozer
#
################################################################################

# changing into binary directory
echo Changing into binary directory
cd bin/

# run the application
echo Running Unimozer
java -cp .:../lib/swing-layout-1.0.3.jar:../lib/bsh-2.0b4.jar:../lib/janino.jar:../lib/beansbinding-1.2.1.jar lu.fisch.unimozer.Main

# move back into the folder where we started
cd ..
